#!/bin/sh
# The test bench: every check that can run on a host with Docker and no
# handheld. From the repository root, in any POSIX shell (Git Bash on
# Windows, as with the other scripts):
#
#   sh scripts/test.sh            everything below
#   sh scripts/test.sh -quick     the same minus the two builds
#
# Checks, one line each on stdout -- PASS <name> <key numbers>,
# FAIL <name> <reason>, SKIP <name> <why> -- and a non-zero exit if any
# FAILed. Progress notes go to stderr so the stdout lines stay parseable.
#
#   build-app   scripts/build-app.sh: the device binary, "built out/xcloud"
#               and the ABI check's "ABI OK" (glibc 2.32).
#   build-host  scripts/build-host.sh: out/host/xcloud and out/host/mkstream.
#   synth       recordings/synth-20s.xcau, generated by scripts/mkstream.sh
#               when missing (20 s of synthetic 720p60, about 40 s to make).
#   clean       the recording replayed through the whole pipeline in the
#               simulator (scripts/sim.sh): the replay| SUMMARY must show
#               shown >= 95% of decoded, skipped <= 30, late <= 2, and every
#               per-second audio| line fail=0 and under <= 2.
#   impaired    the same with -impair "jitter=5,gap=8000:150,loss=1": a
#               SUMMARY with lost > 0 and resync > 0 -- the model dropped
#               units and the resync path ran -- and a clean exit.
#   scale       a short replay with -scale sharp: the CPU 2:1 downscale must
#               engage ("halved on the CPU"), keep the pipeline whole
#               (shown >= 95% of decoded, late <= 2) and not crash. The
#               kernels themselves are checked against plain C, including
#               on aarch64 under QEMU, by scripts/nv12check.sh.
#   launcher    port/XCloud.sh exercised as an SD-card install: it must find
#               the client beside itself, keep another port's gamelist entry
#               while registering its own exactly once, take the client down
#               with it on SIGTERM rather than orphaning it, and fail loudly
#               when only the launcher was copied. The client is stubbed.
#   ui          the UI smoke test: -fake-catalog 60 and a -ui-script that
#               walks the library and quits, with XCLOUD_SIM_SHOTS on. PASS
#               is three or more PNGs; a run that wrote fewer (the client
#               rejected the flags, or stopped at the sign-in screen) is a
#               SKIP, not a FAIL, so a library screen still being built does
#               not fail the bench. A crash (fatal-signal backtrace) does.
#
# Logs: out/host/test/<check>.log, screenshots in out/host/test/shots.
#
# Every simulator run gets its own container name (XCLOUD_SIM_NAME) and a
# hard bound (XCLOUD_SIM_TIMEOUT, coreutils timeout inside the container;
# -quit-after is the client's own, softer, bound), and the host side is
# bounded too. A trap on EXIT runs `docker kill` on every name this run
# used, because a container outlives a killed docker client -- Ctrl-C here
# stops the client, not the container -- and must never outlive the script.
#
# Two things the simulator logs that are NOT failures: SCHED_FIFO is
# refused in the container (-nort keeps that quiet), and ALSA's null device
# reports alsa=0-0ms with the audio servo at adj<0 throughout.
cd "$(dirname "$0")/.." || exit 1

QUICK=0
for a in "$@"; do
	case "$a" in
		-quick) QUICK=1 ;;
		*)
			echo "usage: sh scripts/test.sh [-quick]" >&2
			exit 2 ;;
	esac
done

LOGDIR=out/host/test
SHOTS=$LOGDIR/shots
REC=recordings/synth-20s.xcau
IMPAIR="jitter=5,gap=8000:150,loss=1"
mkdir -p "$LOGDIR"

# Container names unique to this run: the PID plus the time of day, so a
# name can never collide with one left behind by an earlier run that lost
# its trap (docker run --name refuses a duplicate).
RUN=xctest-$$-$(date +%H%M%S)
NAMES=""
NPASS=0; NFAIL=0; NSKIP=0

cleanup() {
	for n in $NAMES; do
		docker kill "$n" >/dev/null 2>&1
	done
}
trap 'rc=$?; cleanup; exit $rc' EXIT
trap 'exit 130' INT TERM HUP

pass() { NPASS=$((NPASS + 1)); echo "PASS $*"; }
fail() { NFAIL=$((NFAIL + 1)); echo "FAIL $*"; }
skip() { NSKIP=$((NSKIP + 1)); echo "SKIP $*"; }
note() { echo "test.sh: $*" >&2; }

# field <key>: the value of key=value on the line read from stdin, first
# match only. Plain string work in awk, no regex, so nothing to escape.
field() {
	awk -v k="$1" '{
		for (i = 1; i <= NF; i++) {
			n = index($i, "=")
			if (n > 1 && substr($i, 1, n - 1) == k) {
				print substr($i, n + 1)
				exit
			}
		}
	}'
}

# num <value>: the value if it is a non-negative integer, else 0, so a
# missing or mangled field can never turn into a shell arithmetic error.
num() {
	case "$1" in
		'' | *[!0-9]*) echo 0 ;;
		*) echo "$1" ;;
	esac
}

size_of() { wc -c <"$1" | tr -d ' '; }

# sim <check> <bound-s> <client args...>: one simulator run, named after
# the check, logged to $LOGDIR/<check>.log, bounded inside the container
# by XCLOUD_SIM_TIMEOUT and outside by coreutils timeout with 30 s to
# spare (the outer one only ever fires if Docker itself has wedged; it
# kills the client, and the docker kill below and the trap get the
# container). $SIM_SHOTS, when set, is forwarded as XCLOUD_SIM_SHOTS.
# Returns the run's exit status: 0 normal, 124 if the inner timeout fired.
sim() {
	check=$1
	bound=$2
	shift 2
	name=$RUN-$check
	NAMES="$NAMES $name"
	outer=""
	command -v timeout >/dev/null 2>&1 && outer="timeout $((bound + 30))"
	(
		[ -n "$SIM_SHOTS" ] && export XCLOUD_SIM_SHOTS="$SIM_SHOTS"
		export XCLOUD_SIM_NAME="$name" XCLOUD_SIM_TIMEOUT="$bound"
		exec $outer sh scripts/sim.sh "$@"
	) >"$LOGDIR/$check.log" 2>&1
	rc=$?
	docker kill "$name" >/dev/null 2>&1
	return $rc
}

# last_line <log>: the last non-empty line, for a FAIL reason.
last_line() { grep -v '^$' "$1" | tail -1; }

# ---- 1. device build ------------------------------------------------------
check_build_app() {
	log=$LOGDIR/build-app.log
	note "build-app: sh scripts/build-app.sh (about 30 s incremental) ..."
	t0=$(date +%s)
	sh scripts/build-app.sh >"$log" 2>&1
	rc=$?
	secs=$(( $(date +%s) - t0 ))
	if [ "$rc" -eq 0 ] && grep -q -F 'built out/xcloud' "$log" && grep -q -F 'ABI OK' "$log" && [ -f out/xcloud ]; then
		pass "build-app out/xcloud $(size_of out/xcloud) bytes, ABI OK, ${secs}s"
	elif [ "$rc" -eq 0 ]; then
		fail "build-app exit 0 but no 'built out/xcloud' + 'ABI OK' in $log"
	else
		fail "build-app exit $rc after ${secs}s: $(last_line "$log") (see $log)"
	fi
}

# ---- 2. host build --------------------------------------------------------
check_build_host() {
	log=$LOGDIR/build-host.log
	note "build-host: sh scripts/build-host.sh ..."
	t0=$(date +%s)
	sh scripts/build-host.sh >"$log" 2>&1
	rc=$?
	secs=$(( $(date +%s) - t0 ))
	if [ "$rc" -eq 0 ] && grep -q -F 'built out/host/xcloud' "$log" && grep -q -F 'built out/host/mkstream' "$log" && [ -f out/host/xcloud ] && [ -f out/host/mkstream ]; then
		pass "build-host out/host/xcloud $(size_of out/host/xcloud) bytes, out/host/mkstream $(size_of out/host/mkstream) bytes, ${secs}s"
	elif [ "$rc" -eq 0 ]; then
		fail "build-host exit 0 but out/host/xcloud or out/host/mkstream not reported built (see $log)"
	else
		fail "build-host exit $rc after ${secs}s: $(last_line "$log") (see $log)"
	fi
}

# ---- 3. the synthetic recording ------------------------------------------
# A file under 5 MB is a generator that was killed mid-write (a good one is
# about 1 MB per second of stream), so it is remade rather than replayed.
check_synth() {
	if [ -f "$REC" ] && [ "$(size_of "$REC")" -ge 5000000 ]; then
		pass "synth $REC present, $(size_of "$REC") bytes"
		return
	fi
	[ -f "$REC" ] && note "synth: $REC is only $(size_of "$REC") bytes, regenerating"
	rm -f "$REC"
	log=$LOGDIR/mkstream.log
	name=$RUN-mkstream
	NAMES="$NAMES $name"
	note "synth: sh scripts/mkstream.sh 20 (about 40 s) ..."
	t0=$(date +%s)
	XCLOUD_SIM_NAME=$name sh scripts/mkstream.sh 20 >"$log" 2>&1
	rc=$?
	docker kill "$name" >/dev/null 2>&1
	secs=$(( $(date +%s) - t0 ))
	if [ "$rc" -eq 0 ] && [ -f "$REC" ] && [ "$(size_of "$REC")" -ge 5000000 ]; then
		pass "synth generated $REC, $(size_of "$REC") bytes, ${secs}s"
	else
		fail "synth mkstream exit $rc after ${secs}s: $(last_line "$log") (see $log)"
	fi
}

# ---- 4. clean replay ------------------------------------------------------
check_clean() {
	log=$LOGDIR/clean.log
	note "clean: replaying $REC (about 35 s) ..."
	sim clean 45 -nort -quit-after 32 -replay "$REC"
	rc=$?
	summary=$(grep -F 'replay| SUMMARY' "$log" | tail -1)
	if [ -z "$summary" ]; then
		fail "clean no replay| SUMMARY (exit $rc): $(last_line "$log") (see $log)"
		return
	fi
	decoded=$(num "$(echo "$summary" | field decoded)")
	shown=$(num "$(echo "$summary" | field shown)")
	skipped=$(num "$(echo "$summary" | field skipped)")
	late=$(num "$(echo "$summary" | field late)")
	fps=$(echo "$summary" | field fps)
	# Every audio| line: fail must be 0 and under at most 2. One awk pass
	# reports how many lines there were, how many broke each rule, and the
	# worst under= seen.
	# awk prints three numbers; splitting them into $1 $2 $3 is the point.
	# shellcheck disable=SC2046
	set -- $(grep -F 'audio|' "$log" | awk '{
		f = -1; u = -1
		for (i = 1; i <= NF; i++) {
			n = index($i, "=")
			if (n > 1) {
				k = substr($i, 1, n - 1); v = substr($i, n + 1) + 0
				if (k == "fail") f = v
				if (k == "under") u = v
			}
		}
		lines++
		if (f != 0) badfail++
		if (u > 2 || u < 0) badunder++
		if (u > maxunder) maxunder = u
	} END { print lines + 0, badfail + 0, badunder + 0, maxunder + 0 }')
	alines=$1; badfail=$2; badunder=$3; maxunder=$4
	why=""
	[ "$decoded" -gt 0 ] || why="$why decoded=0;"
	[ $((shown * 100)) -ge $((decoded * 95)) ] || why="$why shown=$shown < 95% of decoded=$decoded;"
	[ "$skipped" -le 30 ] || why="$why skipped=$skipped > 30;"
	[ "$late" -le 2 ] || why="$why late=$late > 2;"
	[ "$alines" -gt 0 ] || why="$why no audio| lines;"
	[ "$badfail" -eq 0 ] || why="$why $badfail audio| lines with fail>0;"
	[ "$badunder" -eq 0 ] || why="$why $badunder audio| lines with under>2 (max $maxunder);"
	[ "$rc" -eq 0 ] || why="$why exit $rc;"
	if [ -z "$why" ]; then
		pass "clean decoded=$decoded shown=$shown skipped=$skipped late=$late fps=$fps audio: $alines lines fail=0 under<=$maxunder"
	else
		fail "clean$why (see $log)"
	fi
}

# ---- 5. impaired replay ---------------------------------------------------
check_impaired() {
	log=$LOGDIR/impaired.log
	note "impaired: replaying $REC with -impair $IMPAIR (about 35 s) ..."
	sim impaired 45 -nort -quit-after 32 -replay "$REC" -impair "$IMPAIR"
	rc=$?
	summary=$(grep -F 'replay| SUMMARY' "$log" | tail -1)
	if [ -z "$summary" ]; then
		fail "impaired no replay| SUMMARY (exit $rc): $(last_line "$log") (see $log)"
		return
	fi
	lost=$(num "$(echo "$summary" | field lost)")
	resync=$(num "$(echo "$summary" | field resync)")
	discarded=$(num "$(echo "$summary" | field discarded)")
	alost=$(num "$(echo "$summary" | field alost)")
	decoded=$(num "$(echo "$summary" | field decoded)")
	shown=$(num "$(echo "$summary" | field shown)")
	fps=$(echo "$summary" | field fps)
	seed=$(grep -F 'impair:' "$log" | head -1 | field seed)
	why=""
	[ "$lost" -gt 0 ] || why="$why lost=0, the model dropped nothing;"
	[ "$resync" -gt 0 ] || why="$why resync=0, the resync path never ran;"
	[ "$rc" -eq 0 ] || why="$why exit $rc;"
	if [ -z "$why" ]; then
		pass "impaired lost=$lost resync=$resync discarded=$discarded alost=$alost shown=$shown/$decoded fps=$fps seed=$seed exit 0"
	else
		fail "impaired$why (see $log)"
	fi
}

# ---- 6. UI smoke ----------------------------------------------------------
# ---- 6. the CPU downscale -------------------------------------------------
# Short on purpose: the arithmetic is covered by scripts/nv12check.sh, so all
# this has to show is that the path engages and the pipeline survives it.
check_scale() {
	log=$LOGDIR/scale.log
	note "scale: replaying $REC with -scale sharp (about 15 s) ..."
	sim scale 30 -nort -quit-after 12 -replay "$REC" -scale sharp
	rc=$?
	summary=$(grep -F 'replay| SUMMARY' "$log" | tail -1)
	if [ -z "$summary" ]; then
		fail "scale no replay| SUMMARY (exit $rc): $(last_line "$log") (see $log)"
		return
	fi
	decoded=$(num "$(echo "$summary" | field decoded)")
	shown=$(num "$(echo "$summary" | field shown)")
	late=$(num "$(echo "$summary" | field late)")
	why=""
	grep -q -F 'halved on the CPU' "$log" ||
		why="$why -scale sharp did not engage;"
	grep -q -F 'fatal signal' "$log" && why="$why crashed;"
	[ "$decoded" -gt 0 ] || why="$why decoded=0;"
	[ $((shown * 100)) -ge $((decoded * 95)) ] ||
		why="$why shown=$shown < 95% of decoded=$decoded;"
	[ "$late" -le 2 ] || why="$why late=$late > 2;"
	[ "$rc" -eq 0 ] || why="$why exit $rc;"
	if [ -z "$why" ]; then
		pass "scale decoded=$decoded shown=$shown late=$late (640x360 on the CPU)"
	else
		fail "scale$why (see $log)"
	fi
}

check_ui() {
	log=$LOGDIR/ui.log
	rm -rf "$SHOTS"
	mkdir -p "$SHOTS"
	note "ui: -fake-catalog 60 with a scripted walk of the library (up to 30 s) ..."
	SIM_SHOTS=$SHOTS
	# Walks all three bands the D-pad can be in, because since the focus
	# model went in that is where the screen's state lives: Up out of the
	# list to the tabs, Left/Right along them, Down back in. Then a genre
	# entered with Right and left with B, the letter strip, the info panel
	# on X, the shoulders cycling the tab, and the button tester opened
	# and held-B out of. A script that only moved down a flat list would
	# now miss every gesture that changes what is showing -- and the two
	# modal screens (tester, info) have their own input loops, so nothing
	# else covers them at all.
	sim ui 40 -nort -quit-after 30 -fake-catalog 60 -fake-consoles 1 		-ui-script "wait:500,up,wait:300,right,wait:300,right,wait:300,down,wait:300,right,wait:500,B,wait:300,up,wait:300,left,wait:300,down,wait:300,right,wait:300,down,wait:300,X,wait:700,B,wait:400,R1,wait:300,R1,wait:300,R1,wait:600,A,wait:700,hold:B:1100,wait:400,quit"
	rc=$?
	SIM_SHOTS=""
	n=$(find "$SHOTS" -maxdepth 1 -name '*.png' 2>/dev/null | wc -l | tr -d ' ')
	# drm-sim: is the simulated panel's first line; without it the client
	# never started (no binary, no image, no Docker), which is the bench's
	# failure, not a screen that is not there yet.
	if ! grep -q -F 'drm-sim:' "$log"; then
		fail "ui client did not start (exit $rc): $(last_line "$log") (see $log)"
	elif grep -q -F 'fatal signal' "$log"; then
		fail "ui crashed (fatal signal, backtrace in $log), $n PNGs"
	elif [ "$n" -ge 3 ] && [ "$rc" -ne 124 ] && [ "$rc" -ne 137 ]; then
		pass "ui $n PNGs in $SHOTS, exit $rc"
	elif [ "$n" -ge 3 ]; then
		fail "ui $n PNGs but only the hard timeout stopped the run (exit $rc): neither the script's quit nor -quit-after 30 did (see $log)"
	else
		# Fewer than three screens: the flags are not honoured yet, or
		# the run never got past sign-in. The most telling log line, if
		# there is one, goes in the SKIP.
		hint=$(grep -i -E 'unknown|unrecogni|not (yet )?(supported|implemented)|usage:|rejected|missing' "$log" | head -1)
		if [ -n "$hint" ]; then
			hint=": $hint"
		elif grep -q -F 'device code' "$log"; then
			hint=": stayed on the sign-in screen (-fake-catalog not honoured before sign-in yet)"
		fi
		skip "ui $n PNGs, exit $rc$hint (see $log)"
	fi
}

#
# The gamelist merge that scripts/install.sh installs with. Worth a check
# because the failure it guards against is silent and destructive: the
# device's /userdata/roms/ports/gamelist.xml is shared with every other port,
# so a merge that dropped entries would delete PortMaster's metadata and
# nobody would notice until they looked at the Ports list.
#
check_gamelist() {
	log=$LOGDIR/gamelist.log
	dir=$LOGDIR/gamelist
	: > "$log"

	command -v python >/dev/null 2>&1 || {
		skip "gamelist python not found"
		return
	}
	rm -rf "$dir"
	mkdir -p "$dir"
	note "gamelist: merge into a list holding three other ports ..."

	# Three entries that must survive, one of them ours from an earlier
	# install, so this covers both appending and replacing.
	cat > "$dir/device.xml" <<-'XML'
	<?xml version="1.0"?>
	<gameList>
		<game><path>./PortMaster/PortMaster.sh</path><name>PortMaster</name></game>
		<game><path>./DRM Probe.sh</path><name>DRM Probe</name></game>
		<game><path>./PlayTest.sh</path><name>Play Test</name></game>
	</gameList>
	XML

	if ! python tools/gamelist-merge.py --entry port/gamelist.xml \
			--into "$dir/device.xml" --out "$dir/1.xml" >>"$log" 2>&1; then
		fail "gamelist merge failed (see $log)"
		return
	fi
	# Installing twice must not add a second copy of our entry.
	if ! python tools/gamelist-merge.py --entry port/gamelist.xml \
			--into "$dir/1.xml" --out "$dir/2.xml" >>"$log" 2>&1; then
		fail "gamelist second merge failed (see $log)"
		return
	fi
	n1=$(grep -c '<game>' "$dir/1.xml" 2>/dev/null || echo 0)
	n2=$(grep -c '<game>' "$dir/2.xml" 2>/dev/null || echo 0)
	# Count <path> lines only: the merged file is indented one element per
	# line, so a name matching the same word would be counted twice.
	kept=$(grep '<path>' "$dir/2.xml" |
		grep -c -E 'PortMaster\.sh|DRM Probe\.sh|PlayTest\.sh' || echo 0)
	ours=$(grep '<path>' "$dir/2.xml" | grep -c 'Xbox Cloud\.sh' || echo 0)

	# A malformed device gamelist must stop the install, not be replaced.
	printf '<gameList><game><path>x' > "$dir/bad.xml"
	python tools/gamelist-merge.py --entry port/gamelist.xml \
		--into "$dir/bad.xml" --out "$dir/bad.out" >>"$log" 2>&1
	refused=$?

	if [ "$n1" = "4" ] && [ "$n2" = "4" ] && [ "$kept" = "3" ] &&
	   [ "$ours" = "1" ] && [ "$refused" != "0" ]; then
		pass "gamelist 3 kept, ours merged once, re-run idempotent, malformed refused"
	else
		fail "gamelist first=$n1 second=$n2 kept=$kept ours=$ours refused=$refused (see $log)"
	fi
}

# The port launcher, exercised the way a user installs it: a ROM card whose
# ports/ folder already holds somebody else's port, with ours copied in on
# top. Worth a check because this is the ONLY install route that needs no
# terminal, so it is the one most people will use and the one nobody would
# notice breaking -- and because the launcher edits the shared gamelist by
# itself on first run, which must never cost a user their other ports.
#
# The client is stubbed: what is under test is the launcher's discovery of a
# binary relative to itself, its state setup, and that first-run merge. The
# real binary is aarch64 and cannot run here.
check_launcher() {
	log=$LOGDIR/launcher.log
	dir=$LOGDIR/launcher
	: > "$log"

	command -v python3 >/dev/null 2>&1 || {
		skip "launcher python3 not found (the device has it)"
		return
	}
	rm -rf "$dir"
	mkdir -p "$dir/card/ports/xcloud" "$dir/state" "$dir/logs"
	note "launcher: simulating an SD-card install ..."

	# An existing port that must survive, entry and all.
	printf '#!/bin/sh\necho other\n' > "$dir/card/ports/PortMaster.sh"
	cat > "$dir/card/ports/gamelist.xml" <<-'XML'
	<?xml version="1.0"?>
	<gameList>
		<game><path>./PortMaster.sh</path><name>PortMaster</name></game>
	</gameList>
	XML

	# What package.sh lays down, minus the real binary.
	cp port/XCloud.sh          "$dir/card/ports/Xbox Cloud.sh"
	cp port/gamelist.xml       "$dir/card/ports/xcloud/gamelist.xml"
	cp tools/gamelist-merge.py "$dir/card/ports/xcloud/gamelist-merge.py"
	printf '#!/bin/sh\necho "stub $*"\n' > "$dir/card/ports/xcloud/xcloud"
	chmod 755 "$dir/card/ports/xcloud/xcloud" "$dir/card/ports/Xbox Cloud.sh"

	# Separate log directories per run: the launcher truncates its log on
	# every start, so a shared one would leave only the second run's.
	XCLOUD_PORT_STATE="$dir/state" XCLOUD_PORT_LOGS="$dir/logs1" \
		sh "$dir/card/ports/Xbox Cloud.sh" -p1devicepath /dev/input/event3 \
		>>"$log" 2>&1
	rc1=$?
	# Twice, sharing state: the first-run registration must not repeat.
	XCLOUD_PORT_STATE="$dir/state" XCLOUD_PORT_LOGS="$dir/logs2" \
		sh "$dir/card/ports/Xbox Cloud.sh" >>"$log" 2>&1
	rc2=$?

	ran=$(grep -c 'stub -p1devicepath /dev/input/event3' "$dir/logs1/xcloud.log" 2>/dev/null || true)
	ran=$(num "$ran")
	marker=0
	[ -f "$dir/state/.gamelist-registered" ] && marker=1
	games=$(num "$(grep -c '<game>' "$dir/card/ports/gamelist.xml" 2>/dev/null || true)")
	kept=$(num "$(grep '<path>' "$dir/card/ports/gamelist.xml" 2>/dev/null | grep -c 'PortMaster[.]sh' || true)")
	ours=$(num "$(grep '<path>' "$dir/card/ports/gamelist.xml" 2>/dev/null | grep -c 'Xbox Cloud[.]sh' || true)")
	litter=$(ls "$dir/card/ports/"*.new 2>/dev/null | wc -l | tr -d ' ')

	# Copying only the launcher and not the xcloud/ folder is the mistake
	# people will actually make; it must fail loudly rather than silently.
	mkdir -p "$dir/bad/ports"
	cp port/XCloud.sh "$dir/bad/ports/Xbox Cloud.sh"
	XCLOUD_PORT_STATE="$dir/state3" XCLOUD_PORT_LOGS="$dir/logs3" \
		sh "$dir/bad/ports/Xbox Cloud.sh" >>"$log" 2>&1
	badrc=$?
	said=$(num "$(grep -c 'no client binary found' "$dir/logs3/xcloud.log" 2>/dev/null || true)")

	# A killed launcher must take the client with it. If it does not, the
	# client is orphaned and carries on holding the audio device and the
	# DRM plane while EmulationStation comes back over the top -- the menu
	# returns and the game's music keeps playing. Found on hardware.
	#
	# Detected by liveness rather than by process name: the stub keeps
	# touching a file, so "still running" is "the file kept changing after
	# the launcher died", which needs no pgrep and cannot go stale.
	mkdir -p "$dir/sig/ports/xcloud"
	cp port/XCloud.sh "$dir/sig/ports/Xbox Cloud.sh"
	{
		echo '#!/bin/sh'
		echo 'i=0'
		echo 'while [ $i -lt 60 ]; do echo $i > "$0.alive"; sleep 1; i=$((i+1)); done'
	} > "$dir/sig/ports/xcloud/xcloud"
	chmod 755 "$dir/sig/ports/xcloud/xcloud" "$dir/sig/ports/Xbox Cloud.sh"

	XCLOUD_PORT_STATE="$dir/state4" XCLOUD_PORT_LOGS="$dir/logs4" \
		sh "$dir/sig/ports/Xbox Cloud.sh" >>"$log" 2>&1 &
	lpid=$!
	sleep 4
	kill -TERM "$lpid" 2>/dev/null
	sleep 2
	before=$(cat "$dir/sig/ports/xcloud/xcloud.alive" 2>/dev/null || echo none)
	sleep 3
	after=$(cat "$dir/sig/ports/xcloud/xcloud.alive" 2>/dev/null || echo none)
	wait "$lpid" 2>/dev/null
	orphan=0
	[ "$before" != "$after" ] && orphan=1
	# Whatever the result, do not leave one of these behind.
	pkill -f "$dir/sig/ports/xcloud/xcloud" >/dev/null 2>&1 || true

	if [ "$orphan" = "0" ] && [ "$rc1" = "0" ] && [ "$rc2" = "0" ] && [ "$ran" -ge 1 ] &&
	   [ "$marker" = "1" ] && [ "$games" = "2" ] && [ "$kept" = "1" ] &&
	   [ "$ours" = "1" ] && [ "$litter" = "0" ] && [ "$badrc" != "0" ] &&
	   [ "$said" -ge 1 ]; then
		pass "launcher found the client beside itself, registered once, kept the other port, took it down on TERM, failed loudly when incomplete"
	else
		fail "launcher rc=$rc1/$rc2 ran=$ran marker=$marker games=$games kept=$kept ours=$ours litter=$litter badrc=$badrc said=$said orphan=$orphan (see $log)"
	fi
}

# ---- run --------------------------------------------------------------------
if [ "$QUICK" -eq 1 ]; then
	skip "build-app -quick"
	skip "build-host -quick"
else
	check_build_app
	check_build_host
fi
check_synth
check_clean
check_impaired
check_scale
check_ui
check_gamelist
check_launcher

total=$((NPASS + NFAIL + NSKIP))
echo "test.sh: $total checks, $NPASS passed, $NFAIL failed, $NSKIP skipped (logs in $LOGDIR)"
[ "$NFAIL" -eq 0 ]
